### ISSUE TITLE
Suggestion/Request: Settings for SWEP authors to override DWR's auto-detection

### ISSUE THREAD

**Issue by Vuthakral** [modusmogulus/GmodDynamicWeaponReverb#30]
Some SWEPs/bases on Garry's Mod already utilize systems which do what DWR does but specific to those weapons or are weapons which should not have DWR applied to them (e.g. energy weapons, flamethrowers, etc), and I believe some settings which DWR could read from to allow content creators to have influence on it would prove to be beneficial for all.

E.g.:
* `SWEP.DWR_Disable_Reverb = true/false`
* `SWEP.DWR_Disable_Crack = true/false`
* `SWEP.DWR_AmmoOverride = "pistol"`
* `SWEP.DWR_ForceSilenced = true/false`

**Comment by relaxtakenotes** [comment]
sounds interesting. i'll think about it

**Comment by GittyMuh** [comment]
this is an amazing idea. imagine laser type/any type weapons that have a really high rpm creating so many reverbs that overlap with each other and become so loud you cant even use headphones without risk of hearing loss so youd wanna uninstall this addon instantly (DEFINITELY not me >_<' )

**Comment by GittyMuh** [comment]
^^^ i definitely dont relate to my comment i pinkie promise!1!!!

**Comment by relaxtakenotes** [comment]
> Make the sounds muffled when your in a building and in a closed in area, Or just the building option if you like.

is this a separate suggestion or? we apply sound occlusion how it's needed already. for further questions create a separate issue. dont leech plz

**Comment by relaxtakenotes** [comment]
Finally added this after almost a month of procrastinating LoL
It'll need some testing first though and the implementation is probably garbage, but I really wanted it to be easy for weapon developers to modify the vars.
They should be modified serverside, if done otherwise only the client in question will hear an altered result.

weapon.dwr_cracksDisable (bool)
weapon.dwr_reverbDisable (bool)
weapon.dwr_customVolume (float) (from 0 to 1)
weapon.dwr_customAmmoType (string) ('357', 'ar2', 'buckshot', 'pistol', 'smg1', 'other', 'explosions')
weapon.dwr_customIsSuppressed (bool)

**Comment by relaxtakenotes** [comment]
Works good with a test swep I made. Will be in the next workshop update
