### ISSUE TITLE
Sounds are significantly louder outside when the source of gunfire is inside

### ISSUE THREAD

**Issue by tornadorundo** [modusmogulus/GmodDynamicWeaponReverb#31]
I've been messing around with this mod a lot, and I love it honestly. It adds a whole new layer of realism and immersion. There's a slight issue with the way the sound works, though. When a third party is outside and the source of the gunfire is coming from inside, the third party will hear the sounds significantly louder than they would be outside.

I'd say adding some sort of low pass effect on the sound would work, and honestly, I almost feel like switching the sounds of the indoor and outdoor gunfire would work. The outdoor gunfire is more quiet and muffled than the indoor gunfire is (from an outside perspective.)

I'll link a demonstration video below:
https://youtu.be/o8QJShrUvqg

**Comment by relaxtakenotes** [comment]
Sound occlusion takes care of the low pass effect and in this case it was already activated. We can't make it stronger because we can only use default DSP effects. Though suspiciously I don't hear the reverb all that well and from testing I imagine it'd be way louder at that distance. I'll see if the ear position detection is correct and return to you if your issue persists.

**Comment by relaxtakenotes** [comment]
Did some corrections.
- If both ear position and the sound source are outdoors, lowpass effect will not be applied in any case.
- If sound source is distant: If sound source is outdoors, multiply the volume by 2, otherwise half it.
- Tweaked the distance volume fall off.
https://www.youtube.com/watch?v=NWw-u3hvDFw

**Comment by relaxtakenotes** [comment]
pushed to workshop. reopen issue if you think it's still wrong
