### ISSUE TITLE
Suggesiton DWR Whitelist/Blacklist

### ISSUE THREAD

**Issue by FrostbiteTR54** [modusmogulus/GmodDynamicWeaponReverb#45]
I think a option where users can select which weapons are able to use dwr reverb will be good. This setting could be in q (spawn) menu or alternatively added through server convars. With this addition issues with silencers or food sweps could be fixed

**Comment by relaxtakenotes** [comment]
We support silencers in the most major weapon bases already. We reduce the volume of reverb accordingly. However I never seen anyone report any issues with "food sweps" and I believe it could be fixed without the suggested feature in question. Not to say I won't consider it, just pointing it out. I think we'll lean more towards a blacklist as it is easier to blacklist certain outliers rather than whitelist a bunch of weapons that work perfectly fine. So yeah, maybe we'll add that!

**Comment by relaxtakenotes** [comment]
You can try out the github version if you want, I have implemented a blacklist system just now. It'll be pushed to workshop once it's concrete that it doesn't have some dumb bugs
