### ISSUE TITLE
При перезарядке звук снова воспроизводится | When recharging, the sound is played again

### ISSUE THREAD

**Issue by msmr14** [modusmogulus/GmodDynamicWeaponReverb#60]
https://youtu.be/QKZbl-GZipY

**Comment by relaxtakenotes** [comment]
I've noticed that this is an issue. I'm not entirely sure how to fix it because the way we detect shots on the client is by seeing how the ammo count changes. The weapon must have reduced its ammo count when reloading.
Before you ask why we use this method, it's because entityfirebullets seems to be greatly delayed on the client under certain conditions, causing the reverb sound to be out of sync with the actual shot.
I will keep this in the back of my head and this issue open until I figure out a big brain method to fix it...

**Comment by relaxtakenotes** [comment]
After a long time of not even opening the project, I have made a fix. You can get it from the master branch. Tell me how it goes

**Comment by msmr14** [comment]
Да, все хорошо, ошибка пропала, можно заливать в воркшоп, думаю 👀
